#!/usr/bin/env bash

set -e
set -o pipefail

SOURCE_DIR=/home/ubuntu/website
RESOURCES_DIR=/home/ubuntu/website/resources
ENVIRONMENT_FILE="$RESOURCES_DIR/environment-vars"
source $ENVIRONMENT_FILE
echo "source $ENVIRONMENT_FILE" > /home/ubuntu/.bash_profile

id -u patrick &>/dev/null || sudo useradd patrick

# Configure sources
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
curl -sS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
sudo install -T "$RESOURCES_DIR/yarn.list" /etc/apt/sources.list.d/yarn.list
sudo install -T "$RESOURCES_DIR/nodesource.list" /etc/apt/sources.list.d/nodesource.list

# Install packages
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update -yq
sudo apt-get install -yq \
  g++ \
  gcc \
  libpq-dev \
  libxml2 \
  make \
  nginx \
  nodejs \
  software-properties-common \
  ruby \
  ruby-bundler \
  ruby-dev  \
  yarn
sudo apt-get remove certbot -yq
sudo snap install --classic certbot
sudo snap install core
sudo snap refresh core
sudo apt autoremove -yq
sudo /snap/bin/certbot renew --dry-run

# config files
sudo install -T resources/nginx.conf /etc/nginx/nginx.conf
sudo install -T resources/patrick-web.service /etc/systemd/system/patrick-web.service

# cron
"$RESOURCES_DIR/cron/verify-all"
sudo install -T "$RESOURCES_DIR/cron/weekly" /etc/cron.weekly/patrick-web

# systemctl
sudo systemctl enable patrick-web
sudo systemctl daemon-reload

# logging
LOG_DIR="$SOURCE_DIR/log"
sudo mkdir -p "$LOG_DIR"
sudo chmod a+x /home/ubuntu
sudo chmod 0664 -R "$LOG_DIR"
sudo chmod 0774 "$LOG_DIR"
sudo chown -R ubuntu "$LOG_DIR"
sudo chgrp -R ubuntu "$LOG_DIR"
sudo touch /var/log/patrick-web.log
sudo chown patrick /var/log/patrick-web.log

# TODO(patrick): Find a better location for this
mkdir -p /home/ubuntu/website/tmp
chmod -R 777 /home/ubuntu/website/tmp

# ruby
sudo gem install bundler
bundle install

# rails
# TODO(patrick): Generate config/secrets.yml
RAILS_ENV=production bundle exec rake assets:precompile

# restart
sudo service nginx restart
sudo service patrick-web restart

# TODO(patrick): Initialize certbot
