#!/usr/bin/env bash

id -u patrick &>/dev/null || sudo useradd patrick 

sudo apt-get update -yq
sudo apt-get install gcc g++ libpq-dev make nginx ruby ruby-dev ruby-bundler -yq

sudo cp resources/nginx.conf /etc/nginx/nginx.conf
sudo cp resources/patrick-web.service /etc/systemd/system/patrick-web.service
sudo systemctl daemon-reload
sudo touch /var/log/patrick-web.log
sudo chown patrick /var/log/patrick-web.log 

# TODO(patrick): Find a better location for this
mkdir -p /home/ubuntu/website/tmp
chmod -R 777 /home/ubuntu/website/tmp

bundle install

# TODO(patrick): Generate config/secrets.yml

RAILS_ENV=production bundle exec rake assets:precompile

sudo service nginx restart
sudo service patrick-web restart
