#!/usr/bin/env bash

id -u patrick &>/dev/null || sudo useradd patrick 

sudo apt-get update -yq
sudo apt-get install gcc g++ libpq-dev make nginx postgresql ruby ruby-dev ruby-bundler -yq

sudo cp resources/nginx.conf /etc/nginx/nginx.conf
sudo cp resources/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
sudo cp resources/patrick-web.service /etc/systemd/system/patrick-web.service
sudo systemctl daemon-reload
sudo touch /var/log/patrick-web.log
sudo chown patrick /var/log/patrick-web.log 

sudo service nginx restart
sudo service postgresql restart
sudo service patrick-web restart

bundle install
